language: node_js
node_js:
  - "8"
  - "9"
cache:
  directories:
    - node_modules
    - ~/.npm
    - build
git:
  submodules: false
before_install: git submodule update --init
install: npm install
script: npm run test

jobs:
  include:
    - stage: semantic release
      if: branch = master
      node_js: "8"
      script: npm run semantic-release
    - stage: gh-pages
      if: branch = master
      node_js: "8"
      script:
        - npm install @linterhub/schema --force
        - gulp deploy
