language: node_js
node_js: stable
cache:
  directories:
    - node_modules
    - ~/.npm
install:
 - npm install
script:
  - npm run test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
    target_branch: gh-pages
