language: node_js
node_js: stable
cache:
  directories:
    - node_modules
    - ~/.npm
git:
  submodules: false
before_install:
  - git submodule update --init
install:
  - npm install
script:
  - npm run test
before_deploy:
  - npm run travis-deploy-once "npm run semantic-release"
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
    target_branch: gh-pages
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
